### ISSUE TITLE
Choosing Between TypeScript vs JavaScript

### ISSUE THREAD

**Issue by raahul1912** [CombatCovid/backend-hardware-designs-registry#8]
**Choosing Between TypeScript vs JavaScript**

JavaScript is a scripting language which helps you create interactive web pages whereas Typescript is a superset of JavaScript. 
Typescript code needs to be compiled while JavaScript code doesn't need to compile. 
So Typescript designed for the development of a large program that trans compile to JavaScript.

**Advantage of TypeScript over JavaScript**

- TypeScript always highlights errors at compilation time during the time of development, whereas JavaScript points out errors at the runtime.
- TypeScript supports strongly typed or static typing, whereas this is not in JavaScript.

Please add your valuable comments

**Comment by jurra** [comment]
Hey @raahul1912 thanks for sharing, so you recommend to use TS in general? I see you are using it already in the backend. I imagine you are talking in general frontend and backend right?

Would be great to hear what @narration-sd thinks

**Comment by raahul1912** [comment]
@jurra and @narration-sd yes I am already using in backend.

**Comment by narration-sd** [comment]
Greetings to both -- 


-- ah, coming to this page after writing a letter which couldn't mail, I see Rahul is already using it. Let's consider, still I think, as it's good to understand judgements that will help the project. --

So here is what I first said...with a little more distance than now,,,and note I'm suggesting at the end a friendly phone call, where I think we can get good mutual understanding easily!

My take would be that it's possibly suitable for the back-end, if Rahul both already has considerable Typescript experience, and can explain why to use it in this case, vs. attention on the important things which I hear may be the central challenges on the back end actually.

To be straightforward also, it doesn't feel a sound idea to consider it coming into the front-end area, the app and its relations.

I hope that's reasonable and doesn't sound abrupt -- it's late again here and I am in the middle of things getting done -- takes more than a moment to come back to 'earth' :)

Here's some basis, then, which I hope gives some useful ideas:

- in fact I had a long consult inside Bell Laboratories where I created a natural language story interpreter that lasted 20 years, and I wrote it using C++, an extremely tightly type-restricted language like TypeScript, brand new at the time. I liked it for purpose, the object orientation, and got along fine, in the time there was to think things out then, with the typing, especially as that was the key to using it at all. 

- however, many, many persons then and to the present _hate_ the language for the type-hardness, its fundamental. Just lke TypeScript

- type-restrictive languages can be valuable for very complex back-ends, because they can help keep things honest where the details or even the fact of subtle errors would be hidden from persons depending on things being perfect. I've done inner OS work also, and I do know.

  I don't think our back-end has sounded anything like this class, unless I'm mistaken, and we need for the purpose of the project, as its name is telling us, to be efficient and move rapidly, as Jose very well knows. Later, there will be another day...indeed.

  Thus my qualification of the subject at first, that there needs to be knowledge of such a deep topic as TypeScript already. 

  And then the second, that there should be good enough reason understood, why to take the burden into this project. This second point is a balance; facts could move it either way.

- I would like to say that indeed it's fine to learn interesting things on a project, but probably not to get in deep with such activity when from beginning there are other things apparently  like axios and GraphQL which truly are essential. 

  I'd prefer at least as I presently understand things to concentrate attentive sharing and learning there.

- on the kinds of code that operates front ends, back to comparison, the endless flexibility and capability of ES6 Javascript are rather essential, because the challenge is of a different kind of complexity -- and to be able to operate without the handcuffs which will only slow down any work with it.


- in fact, it's always quite possible to write type-safe code in ES6 Javascript...when it is important to do so. 

  on the other side, the ability of ES6 to be flexible with types is a primary 'computer science' theory and facet, equal in all values and depth for its purposes as type-hardness. They are not really conflicting theories, even though we will ever hear some discussions so.

- I feel strongly from practice that one should fundamentally apply what is appropriate, in an depth of understanding the real challenge(s), gathered with thought and attention to built prototypes, giving what is essential of each situation: direct experience with what that situation is. 

  I think that's what we can see to do here.

Ok, this note is probably way too formal, and I don't intend so, just to gound things  -- so I will apologize, and think immediately that Rahul and I should have a Discord-phone chat, as has been so useful when Jose and I are working out things.

Rahul, are you there in Delft, or closer to Asia where I once lived, as I may think; what would be hours we can meet up? I'm here much of the day from 10:00 (24hr) forward, West Coast North America, having too often been up already, well into European hours with Jose...!

Best to both,
Clive

Ah, this doesn't work to reply be email, perhaps  as Rahul doesn't have an email entered -- I'll put it up on GitHub, given that will work better! It takes a bit at beginning days of any project, to get everyone well connected, we do know.

**Comment by narration-sd** [comment]
Ok, you both get to see another of my bad habits - to push Send and then want to do a final edit as I read through. 

So when you read this long reply (too long?), please do it on GitHub - it will come out much better for you, I promise :)

**Comment by DNature** [comment]
Here is my on why typescript is better:
- TypeScript makes code easier to read and understand.
- TypeScript can help us to avoid painful bugs that developers commonly run into when writing JavaScript by type checking the code.
- Powerful type system, including generics.

**Comment by narration-sd** [comment]
Thanks, @DNature  --

@raahul1912 has experience, and will be using it on his back-end work.

You are right about some advantages, when they are the ones apropos to the task. We will always have to balance, and no method is ever the sensible one for every situation.

That makes things fun, I think -- and the more you know, (and don't get lost in the Savannah) , the better things your imagination and insight will guide you to.

We'll  have to meet later on the project, but thanks for your thoughts. I had experience with presons from various Africa when I lived in Europe, and think it can be pretty exciting there :)

Best,
Clive

**Comment by DNature** [comment]
Sure @narration-sd. However, i'm also working on the backend part of this project. Nice to meet you :)

**Comment by narration-sd** [comment]
ok, things move fast...are you also known as @nature, I may now realize?  Then it would connect with Jose and my views, converations -- and our first one...welcome...

**Comment by raahul1912** [comment]
We are going with TS and closing this issue.
